steps:
  - id: build_image
    name: "gcr.io/cloud-builders/docker"
    entrypoint: make
    args: [
      "docker_build"
    ] 
  - id: push_image
    name: "gcr.io/cloud-builders/docker"
    entrypoint: make
    args: [
      "docker_push_image_to_repo_artifact"
    ] 
  - id: deploy_cloud_run
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: make
    args: ['gcp_deploy_run']

options:
  logging: CLOUD_LOGGING_ONLY
